### ISSUE TITLE
sensen is watering

### ISSUE THREAD

**Issue by siroiyaksa** [QSCTech/sensen-good-good-study#2]

**Comment by richard1122** [comment]
表示关注...

**Comment by DreaminginCodeZH** [comment]
Now @Senorsen is back into copying homework.

**Comment by leeleo3x** [comment]
±íÊ¾Ö§³Ö

Li Ao
Zhejiang University

**Comment by Hexcles** [comment]
@leeleo3x WTH?

**Comment by leeleo3x** [comment]
@Hexcles QAQ It seems that there is something wrong with my email client

**Comment by HetongWang** [comment]
@Hexcles 这个缩写有点眼熟。。

**Comment by vxst** [comment]
Sensen is watering?VXSTOn 周三, 1月 7, 2015 at 2:42 下午,  QSCTech/sensen-good-good-study <reply@reply.github.com> wrote:            @Hexcles 这个缩写有点眼熟。。

**Comment by AprilWong** [comment]
☂☂☂umbrella...

**Comment by DemoHn** [comment]
森森要好好学信号与系统不然要挂==

**Comment by potaty** [comment]
森森加油。。。不过这学期窝也要挂科啦T T

**Comment by fifth** [comment]
有点厉害的学习监控网

**Comment by leeleo3x** [comment]
This repo has zha chu many people......

Li Ao
Zhejiang University

**Comment by DreaminginCodeZH** [comment]
“这样我就有更多时间来玩了”——森森

**Comment by Qusic** [comment]
全世界的人都要知道森森挂科了。。

**Comment by Alexsunyx** [comment]
挂科而已 慌毛线 `(*∩_∩*)′

**Comment by vxst** [comment]
不要这么说 会带坏森森的VXST

**Comment by DreaminginCodeZH** [comment]
@VXST 单挺娘你每次说话最后都要带上VXST是什么口癖→_→

**Comment by Aremand** [comment]
你们为什么要在森森好好学习repo下面水！

**Comment by vxst** [comment]
那样就强调了我是VXST
