### ISSUE TITLE
森森你连导数都没记住( ⊙ o ⊙ )！。

### ISSUE THREAD

**Issue by zenozeng** [QSCTech/sensen-good-good-study#4]

**Comment by xqyww123** [comment]
据说x的倒数是1/x

**Comment by sunoru** [comment]
hhhhhhh
________________________________
发件人: Xero Essential<mailto:notifications@github.com>
发送时间: ‎2015/‎1/‎7 18:26
收件人: QSCTech/sensen-good-good-study<mailto:sensen-good-good-study@noreply.github.com>
主题: Re: [sensen-good-good-study] 森森你连导数都没记住( ⊙ o ⊙ )！。 (#4)

据说x的倒数是1/x

---

**Comment by zenozeng** [comment]
森森你会背了吗？

**Comment by leeleo3x** [comment]
哈哈哈哈，年度最佳233333333

**Comment by Armour** [comment]
倒树是啥树呀0 0

**Comment by Senorsen** [comment]
as easy as a pie...

**Comment by zenozeng** [comment]
@Senorsen 说出所有六个三角函数的导数？

**Comment by DemoHn** [comment]
曾大神这是在卖萌嘛=w=
突然想到导数可以这么算：` (sin x)' = [(e^jx-e^-jx)/2j]' = [e^jx+e^-jx]*j/(2j) = [e^jx+e^-jx]/2 = cos x `
23333333~~

**Comment by vxst** [comment]
森森连倒数都没记住你就让他学复变。。VXST

**Comment by DemoHn** [comment]
不，这叫信号与系统=w=一门比微积分简单得多的课~~

**Comment by vxst** [comment]
信号与系统不是依赖微积分？你这样装软件包森森要跑不起来的

**Comment by DemoHn** [comment]
关键是这样就能把12个三角函数都能记下来啊~~包括cosh sinh csch啊什么的QAQ=w=

------------------
     天有涯 · 心无疆  
卢名川    DemoHn
GitHub: DemoHn
Codesigner / QSCer / Linuxer
Tel: 15858287622   / 657622 (ZJU)


 




------------------ 原始邮件 ------------------
发件人: "Shan Thomas";<notifications@github.com>;
发送时间: 2015年1月19日(星期一) 中午11:41
收件人: "QSCTech/sensen-good-good-study"<sensen-good-good-study@noreply.github.com>; 
抄送: "DemoHn"<601790183@qq.com>; 
主题: Re: [sensen-good-good-study] 森森你连导数都没记住( ⊙ o ⊙ )！。 (#4)



信号与系统不是依赖微积分？你这样装软件包森森要跑不起来的

**Comment by Senorsen** [comment]
Thanks & sorry but do not disturb please...

(except zengdashen. )
