### ISSUE TITLE
我想BG所有回复者

### ISSUE THREAD

**Issue by Coxious** [QSCTech/sensen-good-good-study#6]
RT
让我BG吧

**Comment by sunoru** [comment]
好的呀~~





发件人: Coxious
发送时间: ‎2015‎年‎1‎月‎8‎日, ‎星期四 ‎19‎:‎24
收件人: QSCTech/sensen-good-good-study





RT
让我BG吧

**Comment by vxst** [comment]
我也要--@sunoru 感觉概率论要挂科了...VXST

**Comment by clarkok** [comment]
闻BG粗！

张靖超 / Clarkok Zhang
计算机科学与技术
http://www.clarkok.com/

**Comment by Coxious** [comment]
你们好过分！！！

**Comment by Armour** [comment]
好啊好啊 （是不是来晚了QUQ

**Comment by Aremand** [comment]
就算来晚了也要求bg！

**Comment by xqyww123** [comment]
强行回复！

**Comment by zenozeng** [comment]
我能 reopen 吗？

**Comment by zhudhjen** [comment]
强行回复！

**Comment by potaty** [comment]
QAQ
