### ISSUE TITLE
森森你的学习日记二呢？

### ISSUE THREAD

**Issue by zenozeng** [QSCTech/sensen-good-good-study#8]
https://blog.senorsen.com/2015%E5%AF%92%E5%81%87-%E5%AD%A6%E4%B9%A0%E6%97%A5%E8%AE%B0%E4%B8%80%EF%BC%9A%E5%A4%8D%E4%B9%A0%E5%BE%AE%E7%A7%AF%E5%88%86/

**Comment by Senorsen** [comment]
QAQ
